### PR TITLE
T6684: new Debian package repo snapshot logic

### PR DESCRIPTION
**Pull request by HollyGurza**
save information about all installed packages and teir source repo, including a temporary packages

list of packages will stored in the file `chroot.packages.all.info`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T6684

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by dmbaturin — APPROVED** [review]

**Comment by c-po** [comment]
We do not use this package during our build process.

Any reason to not place it in build hooks? https://github.com/vyos/vyos-build/tree/current/data/live-build-config/hooks/live

**Comment by HollyGurza** [comment]
> We do not use this package during our build process.
> 
> Any reason to not place it in build hooks? https://github.com/vyos/vyos-build/tree/current/data/live-build-config/hooks/live

we cannot use build hooks because we should to save information about temporary packages but when hooks are working this information is already cleaned

**Comment by dmbaturin** [comment]
>We do not use this package during our build process.

There was a plan to use it for Kim's fixed to the raw image build process, which we ended up not using because the new flavor system uses a different process. But for making snapshots during the release process we'll need to install it on the build host. We should probably make a PR to use this package in the build container image.

**Comment by HollyGurza** [comment]
i think this PR can be closed, the actual patch is stored in the vyos-build repo
(https://github.com/vyos/vyos-build/pull/758)

**Pull request closed without merging**
